=== coolio986/ratical/configuration/boards/board-definition.schema.json
{
	"$schema": "https://json-schema.org/draft-07/schema",
	"$id": "https://github.com/coolio986/ratical/board-definition.schema.json",
	"title": "Control Board",
	"description": "A 3d printer control board",
	"type": "object",
	"additionalProperties": false,
	"properties": {
		"$schema": { "type": "string" },
		"id": {
			"description": "The path for serial communication with this MCU",
			"type": "string"
		},
		"name": {
			"description": "The name of the control board",
			"type": "string"
		},
		"manufacturer": {
			"description": "The name of the manufacturer of this board",
			"type": "string"
		},
		"firmwareBinaryName": {
			"description": "The firmware binary filename in Ratical",
			"type": "string"
		},
		"compileScript": {
			"description": "The path to the compilation script if the board supports automatic firmware compilation, relative to the board definition directory",
			"type": "string"
		},
		"flashScript": {
			"description": "The path to the flashing script if the board supports automatic firmware flashing, relative to the board definition directory",
			"type": "string"
		},
		"flashInstructions": {
			"description": "Instructions for how to make sure the board can be automatically flashed",
			"type": "string"
		},
		"documentationLink": {
			"description": "Link to the Ratical configuration for this board",
			"type": "string"
		},
		"manualFileName": {
			"description": "The filename of the manual for this board, should be placed in the board directory.",
			"type": "string"
		},
		"wireDiagramFileName": {
			"description": "The filename of the wire diagram for this board, should be placed in the board directory.",
			"type": "string"
		},
		"boardImageFileName": {
			"description": "The filename of the image of this board, should be placed in the board directory.",
			"type": "string"
		},
		"isToolboard": {
			"description": "Whether this controlboard is a toolboard",
			"type": "boolean"
		},
		"isHost": {
			"description": "Whether this is the host computer Ratical is running on (used for Pi)",
			"type": "boolean"
		},
		"serialPath": {
			"description": "This property is only required for host boards. It is the path to the serial port to use for communication with the host mcu",
			"type": "string"
		},
		"disableAutoFlash": {
			"description": "Whether to disable automatic flashing of this board",
			"type": "boolean"
		},
		"firmwareOptions": {
			"description": "Advanced Kalico menuconfig symbols (without the CONFIG_ prefix) to expose as opt-in firmware options during flashing. Availability, labels and help text are resolved from the installed Kalico branch's Kconfig at query time; symbols whose dependencies are not met for this board are hidden.",
			"type": "array",
			"items": {
				"type": "string"
			}
		},
		"hasQuirksFiles": {
			"description": "Whether this board has a quirks file that needs to be loaded (must be called quirks.cfg and quirks-toolboard.cfg)",
			"type": "boolean"
		},
		"alternativePT1000Resistor": {
			"description": "The value of an optional resistor used for PT1000 sensors, if different from the default 4700",
			"type": "number"
		},
		"thermistorPullup": {
			"description": "The value of the pullup resistor used for thermistors, if different from the default 4700",
			"type": "number"
		},
		"driverCount": {
			"description": "How many drivers this board has",
			"type": "number"
		},
		"hasMcuTempSensor": {
			"description": "Whether this board has an MCU temperature sensor, default is true",
			"type": "boolean"
		},
		"outputPins": {
			"description": "Output pin definitions. Some boards have safety features that require a pin to be pulled high to enable power, such as the SKR2.",
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"name": {
						"description": "The name of the feature",
						"type": "string"
					},
					"pin": {
						"type": "string"
					},
					"value": {
						"type": "number",
						"maximum": 1,
						"minimum": 0
					},
					"shutdownValue": {
						"type": "number",
						"maximum": 1,
						"minimum": 0
					}
				}
			}
		},
		"customSections": {
			"description": "Custom sections for this board",
			"type": "object",
			"additionalProperties": false,
			"patternProperties": {
				"^\\S+$": {
					"type": "object",
					"properties": {
						"name": {
							"description": "The name of the custom section",
							"type": "string"
						},
						"isPerToolhead": {
							"description": "Whether custom section is per toolhead. Default is true. If true, `name` must be specified. If there is more than one toolhead, the toolhead index will be appended to the name in the generated config like `name_t0`, `name_t1`, etc. Note that there is currently no way for a per-toolhead custom section to have different parameters per toolhead, including referencing another per-toolhead section. Pin references will be automatically adjusted per-toolhead index. If `isPerToolhead` is false, the custom section is global, and must not contain pin references.",
							"type": "boolean"
						},
						"parameters": {
							"description": "The parameters for this custom section",
							"type": "object",
							"additionalProperties": false,
							"patternProperties": {
								"^\\S+$": {
									"description": "A parameter and value for this custom section",
									"oneOf": [{ "type": "number" }, { "type": "string" }, { "type": "boolean" }]
								}
							}
						},
						"comments": {
							"description": "Comments for this custom section",
							"type": "array",
							"items": {
								"type": "string"
							}
						}
					},
					"required": ["parameters"]
				}
			}
		},
		"invertPinLogic": {
			"description": "A list of pins to invert the logic of",
			"type": "array",
			"items": {
				"type": "string"
			}
		},
		"motorSlots": {
			"description": "A specification of the motor slots available on this board",
			"type": "object",
			"patternProperties": {
				"^\\S+$": {
					"type": "object",
					"description": "The settings for a motor slot",
					"properties": {
						"title": {
							"type": "string"
						},
						"step_pin": {
							"type": "string"
						},
						"dir_pin": {
							"type": "string"
						},
						"enable_pin": {
							"type": "string"
						},
						"diag_pin": {
							"type": "string"
						},
						"endstop_pin": {
							"type": "string"
						},
						"uart_pin": {
							"type": "string"
						},
						"uart_address": {
							"type": "string"
						},
						"rx_pin": {
							"type": "string"
						},
						"tx_pin": {
							"type": "string"
						},
						"cs_pin": {
							"type": "string"
						},
						"spi_bus": {
							"type": "string"
						},
						"spi_software_mosi_pin": {
							"type": "string"
						},
						"spi_software_miso_pin": {
							"type": "string"
						},
						"spi_software_sclk_pin": {
							"type": "string"
						}
					},
					"additionalProperties": false,
					"required": ["step_pin", "dir_pin", "enable_pin", "title", "uart_pin", "cs_pin"]
				}
			}
		},
		"stepperSPI": {
			"description": "Which settings to use for SPI stepper drivers",
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"software": {
					"description": "Whether to use software SPI",
					"type": "object",
					"additionalProperties": false,
					"required": ["sclk", "mosi", "miso"],
					"properties": {
						"sclk": {
							"description": "The clock pin",
							"type": "string"
						},
						"mosi": {
							"description": "The mosi pin",
							"type": "string"
						},
						"miso": {
							"description": "The miso pin",
							"type": "string"
						}
					}
				},
				"hardware": {
					"description": "Which SPI bus to use if using hardware spi",
					"type": "object",
					"required": ["bus"],
					"additionalProperties": false,
					"properties": {
						"bus": {
							"description": "The SPI bus to use",
							"type": "string"
						}
					}
				}
			}
		},
		"hotendHeater": {
			"description": "Board-specific settings to use for the hotend heater",
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"maxPower": {
					"description": "The maximum power for the hotend heater",
					"type": "object",
					"additionalProperties": false,
					"properties": {
						"value": { "description": "Max power (0.0-1.0)", "type": "number" },
						"comment": { "description": "Optional comment to include in generated config", "type": "string" }
					},
					"required": ["value"]
				},
				"pwmCycleTime": {
					"description": "The PWM cycle time for the hotend heater",
					"type": "object",
					"additionalProperties": false,
					"properties": {
						"value": { "description": "The PWM cycle time (seconds)", "type": "number" },
						"comment": { "description": "Optional comment to include in generated config", "type": "string" }
					},
					"required": ["value"]
				}
			}
		},
		"partCoolingFan": {
			"description": "Board-specific settings to use for part cooling fan control",
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"maxPower": {
					"description": "The maximum power for the part cooling fan",
					"type": "object",
					"additionalProperties": false,
					"properties": {
						"value": { "description": "Max power (0.0-1.0)", "type": "number" },
						"comment": { "description": "Optional comment to include in generated config", "type": "string" }
					},
					"required": ["value"]
				},
				"inputVoltagePwmCycleTime": {
					"description": "The PWM cycle time for part cooling fan control when using input voltage control (e.g. 2-pin and 3-pin fans).",
					"type": "object",
					"additionalProperties": false,
					"properties": {
						"value": { "description": "The cycle time value (seconds)", "type": "number" },
						"comment": { "description": "Optional comment to include in generated config", "type": "string" }
					},
					"required": ["value"]
				}
			}
		},
		"toolheadCoolingFan": {
			"description": "Board-specific settings to use for toolhead cooling fan control",
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"maxPower": {
					"description": "The maximum power for the toolhead cooling fan",
					"type": "object",
					"additionalProperties": false,
					"properties": {
						"value": { "description": "Max power (0.0-1.0)", "type": "number" },
						"comment": { "description": "Optional comment to include in generated config", "type": "string" }
					},
					"required": ["value"]
				},
				"inputVoltagePwmCycleTime": {
					"description": "The PWM cycle time for toolhead cooling fan control when using input voltage control (e.g. 2-pin and 3-pin fans)",
					"type": "object",
					"additionalProperties": false,
					"properties": {
						"value": { "description": "The cycle time value (seconds)", "type": "number" },
						"comment": { "description": "Optional comment to include in generated config", "type": "string" }
					},
					"required": ["value"]
				}
			}
		},
		"ADXL345SPI": {
			"description": "Which settings to use for the ADXL345 accelerometer",
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"software": {
					"description": "Whether to use software SPI",
					"type": "object",

					"additionalProperties": false,
					"properties": {
						"sclk": {
							"description": "The clock pin",
							"type": "string"
						},
						"mosi": {
							"description": "The mosi pin",
							"type": "string"
						},
						"miso": {
							"description": "The miso pin",
							"type": "string"
						}
					}
				},
				"hardware": {
					"description": "Which SPI bus to use if using hardware spi",
					"type": "object",
					"additionalProperties": false,
					"properties": {
						"bus": {
							"description": "The SPI bus to use",
							"type": "string"
						}
					}
				},
				"cs_pin": {
					"description": "The chip select pin",
					"type": "string"
				},
				"axesMap": {
					"description": "Optional axes mapping for the accelerometer. Default is 'x, z, y'",
					"type": "string"
				}
			}
		},
		"LIS2DW": {
			"description": "Which settings to use for the ADXL345 accelerometer",
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"software": {
					"description": "Whether to use software SPI",
					"type": "object",

					"additionalProperties": false,
					"properties": {
						"sclk": {
							"description": "The clock pin",
							"type": "string"
						},
						"mosi": {
							"description": "The mosi pin",
							"type": "string"
						},
						"miso": {
							"description": "The miso pin",
							"type": "string"
						}
					}
				},
				"hardware": {
					"description": "Which SPI bus to use if using hardware spi",
					"type": "object",
					"additionalProperties": false,
					"properties": {
						"bus": {
							"description": "The SPI bus to use",
							"type": "string"
						}
					}
				},
				"cs_pin": {
					"description": "The chip select pin",
					"type": "string"
				},
				"axesMap": {
					"description": "Optional axes mapping for the accelerometer. Default is 'x, z, y'",
					"type": "string"
				}
			}
		},
		"integratedDrivers": {
			"description": "Describes the drivers integrated on this board, if any",
			"type": "object",
			"additionalProperties": true,
			"properties": {
				"x": {
					"description": "The driver for the X axis",
					"type": "string"
				},
				"y": {
					"description": "The driver for the Y axis",
					"type": "string"
				},
				"z": {
					"description": "The driver for the Z axis",
					"type": "string"
				},
				"z1": {
					"description": "The driver for the Z axis",
					"type": "string"
				},
				"z2": {
					"description": "The driver for the Z axis",
					"type": "string"
				},
				"extruder": {
					"description": "The driver for the E axis",
					"type": "string"
				}
			}
		},
		"driverVoltages": {
			"description": "The supported stepper voltages. 24, 36, 48, 56 and 60 is supported. Default is 24 only.",
			"type": "array",
			"items": {
				"type": "number"
			}
		},
		"extruderlessConfig": {
			"description": "The name of an extruderless config (used for 5 driver boards to support 6 driver printers)",
			"type": "string"
		},
		"fourPinFanConnectorCount": {
			"description": "How many 4 pin fan connectors this board has",
			"type": "number"
		},
		"dfu": {
			"description": "DFU Flashing details",
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"dfuBootImage": {
					"description": "Path to a picture for locating the buttons and/or jumpers required to boot into DFU mode",
					"type": "string"
				},
				"flashDevice": {
					"description": "A string containing the vendor and device id to use as the flash target, eg 0483:df11",
					"type": "string"
				},
				"instructions": {
					"description": "Instruction steps for how to boot into DFU mode",
					"type": "array",
					"items": {
						"type": "string"
					}
				},
				"reminder": {
					"description": "Post-flashing reminders, if any.",
					"type": "string"
				},
				"hasBoot0Jumper": {
					"description": "Whether this board has a boot0 jumper",
					"type": "boolean"
				}
			},
			"required": ["dfuBootImage", "flashDevice", "instructions", "hasBoot0Jumper"]
		},
		"sdFileName": {
			"description": "The filename for the firmware binary when flashing via SD card",
			"type": "string"
		}
	},
	"required": ["id", "name", "manufacturer", "firmwareBinaryName", "compileScript", "documentationLink", "driverCount"]
}

=== coolio986/ratical/configuration/boards/btt-ebb42-12/board-definition.json
{
	"$schema": "../board-definition.schema.json",
	"boardImageFileName": "board.webp",
	"manualFileName": "manual.pdf",
	"wireDiagramFileName": "wiring.drawio.svg",
	"isToolboard": true,
	"name": "EBB42 v1.2",
	"manufacturer": "BIGTREETECH",
	"id": "btt-ebb42-12",
	"firmwareBinaryName": "firmware-btt-ebb42-12.bin",
	"compileScript": "compile.sh",
	"flashScript": "flash.sh",
	"documentationLink": "https://github.com/coolio986/ratical/docs/toolboards/btt/ebb-42-12",
	"driverCount": 1,
	"integratedDrivers": {
		"extruder": "BTT-TMC2209-13"
	},
	"alternativePT1000Resistor": 2200,
	"dfu": {
		"flashDevice": "0483:df11",
		"dfuBootImage": "dfubooting.png",
		"instructions": [
			"Connect the board via USB to the Raspberry Pi",
			"Make sure the board is powered (you can use usb power by placing a jumper on the VBUS pins)",
			"Press and hold the BOOT button on the board.",
			"Press and release the RESET button on the board.",
			"Release the BOOT button."
		],
		"hasBoot0Jumper": false
	},
	"ADXL345SPI": {
		"cs_pin": "PB12",
		"software": {
			"sclk": "PB10",
			"mosi": "PB11",
			"miso": "PB2"
		}
	}
}

=== coolio986/ratical/configuration/boards/btt-skr-3-ez/board-definition.json
{
	"$schema": "../board-definition.schema.json",
	"boardImageFileName": "board.webp",
	"manualFileName": "manual.pdf",
	"wireDiagramFileName": "wiring.drawio.svg",
	"name": "SKR 3 EZ H743",
	"manufacturer": "BIGTREETECH",
	"id": "btt-skr-3-ez",
	"firmwareBinaryName": "firmware-btt-skr-3-ez.bin",
	"compileScript": "compile.sh",
	"flashScript": "flash.sh",
	"documentationLink": "https://github.com/coolio986/ratical/docs/boards/btt/skr-3-ez",
	"driverCount": 5,
	"driverVoltages": [24, 36, 48, 56],
	"alternativePT1000Resistor": 1000,
	"dfu": {
		"flashDevice": "0483:df11",
		"dfuBootImage": "dfubooting.png",
		"instructions": [
			"Connect the board via USB to the Raspberry Pi",
			"Make sure the board is powered (you can use usb power by placing a jumper on the VBUS pins)",
			"Press and hold the BOOT button on the board.",
			"Press and release the RESET button on the board.",
			"Release the BOOT button."
		],
		"hasBoot0Jumper": false
	},
	"extruderlessConfig": "config-3z.cfg",
	"ADXL345SPI": {
		"cs_pin": "PB12",
		"hardware": {
			"bus": "spi2"
		}
	},
	"stepperSPI": {
		"software": {
			"sclk": "PE14",
			"mosi": "PE13",
			"miso": "PE15"
		}
	},
	"motorSlots": {
		"X": {
			"title": "X",
			"enable_pin": "PD6",
			"step_pin": "PD4",
			"dir_pin": "PD3",
			"uart_pin": "PD5",
			"cs_pin": "PD5",
			"diag_pin": "PC1",
			"endstop_pin": "PC1",
			"spi_software_mosi_pin": "PE13",
			"spi_software_miso_pin": "PE15",
			"spi_software_sclk_pin": "PE14"
		},
		"Y": {
			"title": "Y",
			"enable_pin": "PD1",
			"step_pin": "PA15",
			"dir_pin": "PA8",
			"uart_pin": "PD0",
			"cs_pin": "PD0",
			"diag_pin": "PC3",
			"endstop_pin": "PC3",
			"spi_software_mosi_pin": "PE13",
			"spi_software_miso_pin": "PE15",
			"spi_software_sclk_pin": "PE14"
		},
		"Z": {
			"title": "Z",
			"enable_pin": "PE0",
			"step_pin": "PE2",
			"dir_pin": "PE3",
			"uart_pin": "PE1",
			"cs_pin": "PE1",
			"diag_pin": "PC0",
			"endstop_pin": "PC0",
			"spi_software_mosi_pin": "PE13",
			"spi_software_miso_pin": "PE15",
			"spi_software_sclk_pin": "PE14"
		},
		"E0": {
			"title": "E0",
			"enable_pin": "PC7",
			"step_pin": "PD15",
			"dir_pin": "PD14",
			"uart_pin": "PC6",
			"cs_pin": "PC6",
			"diag_pin": "PC2",
			"endstop_pin": "PC2",
			"spi_software_mosi_pin": "PE13",
			"spi_software_miso_pin": "PE15",
			"spi_software_sclk_pin": "PE14"
		},
		"E1": {
			"title": "E1",
			"enable_pin": "PD13",
			"step_pin": "PD11",
			"dir_pin": "PD10",
			"uart_pin": "PD12",
			"cs_pin": "PD12",
			"diag_pin": "PA0",
			"endstop_pin": "PA0",
			"spi_software_mosi_pin": "PE13",
			"spi_software_miso_pin": "PE15",
			"spi_software_sclk_pin": "PE14"
		}
	}
}

=== coolio986/ratical/configuration/boards/fysetc-spider/board-definition.json
{
	"$schema": "../board-definition.schema.json",
	"boardImageFileName": "board.webp",
	"name": "Spider v1.1",
	"manufacturer": "Fysetc",
	"id": "fysetc-spider",
	"firmwareBinaryName": "firmware-fysetc-spider.bin",
	"firmwareOptions": ["WANT_STEPPER_OPTIMIZED_BOTH_EDGE", "HIGH_PREC_STEP"],
	"compileScript": "compile.sh",
	"flashScript": "flash.sh",
	"driverCount": 8,
	"driverVoltages": [24],
	"flashInstructions": "Flashing only works if Fysetc's 32-bit bootloader is installed on the MCU (default since Spider v1.1).",
	"documentationLink": "https://github.com/coolio986/ratical/docs/boards/fysetc/spider-11",
	"ADXL345SPI": {
		"cs_pin": "PA4",
		"software": {
			"sclk": "PA5",
			"mosi": "PA7",
			"miso": "PA6"
		}
	},
	"stepperSPI": {
		"software": {
			"sclk": "PE12",
			"mosi": "PE14",
			"miso": "PE13"
		}
	},
	"motorSlots": {
		"X-MOT": {
			"title": "X-MOT",
			"enable_pin": "PE9",
			"step_pin": "PE11",
			"dir_pin": "PE10",
			"uart_pin": "PE7",
			"cs_pin": "PE7",
			"diag_pin": "PB14",
			"endstop_pin": "PB14",
			"spi_software_mosi_pin": "PE14",
			"spi_software_miso_pin": "PE13",
			"spi_software_sclk_pin": "PE12"
		},
		"Y-MOT": {
			"title": "Y-MOT",
			"enable_pin": "PD9",
			"step_pin": "PD8",
			"dir_pin": "PB12",
			"uart_pin": "PE15",
			"cs_pin": "PE15",
			"diag_pin": "PB13",
			"endstop_pin": "PB13",
			"spi_software_mosi_pin": "PE14",
			"spi_software_miso_pin": "PE13",
			"spi_software_sclk_pin": "PE12"
		},
		"Z-MOT": {
			"title": "Z-MOT",
			"enable_pin": "PD15",
			"step_pin": "PD14",
			"dir_pin": "PD13",
			"uart_pin": "PD10",
			"cs_pin": "PD10",
			"diag_pin": "PA0",
			"endstop_pin": "PA0",
			"spi_software_mosi_pin": "PE14",
			"spi_software_miso_pin": "PE13",
			"spi_software_sclk_pin": "PE12"
		},
		"E0-MOT": {
			"title": "MOTOR 3",
			"enable_pin": "PD4",
			"step_pin": "PD5",
			"dir_pin": "PD6",
			"uart_pin": "PD7",
			"cs_pin": "PD7",
			"diag_pin": "PA1",
			"endstop_pin": "PA1",
			"spi_software_mosi_pin": "PE14",
			"spi_software_miso_pin": "PE13",
			"spi_software_sclk_pin": "PE12"
		},
		"E1-MOT": {
			"title": "E1-MOT",
			"enable_pin": "PE5",
			"step_pin": "PE6",
			"dir_pin": "PC13",
			"uart_pin": "PC14",
			"cs_pin": "PC14",
			"diag_pin": "PA2",
			"endstop_pin": "PA2",
			"spi_software_mosi_pin": "PE14",
			"spi_software_miso_pin": "PE13",
			"spi_software_sclk_pin": "PE12"
		},
		"E2-MOT": {
			"title": "E2-MOT",
			"enable_pin": "PE3",
			"step_pin": "PE2",
			"dir_pin": "PE4",
			"uart_pin": "PC15",
			"cs_pin": "PC15",
			"diag_pin": "PA3",
			"endstop_pin": "PA3",
			"spi_software_mosi_pin": "PE14",
			"spi_software_miso_pin": "PE13",
			"spi_software_sclk_pin": "PE12"
		},
		"E3-MOT": {
			"title": "E3-MOT",
			"enable_pin": "PE8",
			"step_pin": "PD12",
			"dir_pin": "PC4",
			"uart_pin": "PA15",
			"cs_pin": "PA15",
			"spi_software_mosi_pin": "PE14",
			"spi_software_miso_pin": "PE13",
			"spi_software_sclk_pin": "PE12"
		},
		"E4-MOT": {
			"title": "E4-MOT",
			"enable_pin": "PC5",
			"step_pin": "PE1",
			"dir_pin": "PE0",
			"uart_pin": "PD11",
			"cs_pin": "PD11",
			"spi_software_mosi_pin": "PE14",
			"spi_software_miso_pin": "PE13",
			"spi_software_sclk_pin": "PE12"
		}
	}
}

=== coolio986/ratical/configuration/boards/btt-skr-pro-12/board-definition.json
{
	"$schema": "../board-definition.schema.json",
	"boardImageFileName": "board.webp",
	"manualFileName": "manual.pdf",
	"name": "SKR Pro v1.2",
	"manufacturer": "BIGTREETECH",
	"id": "btt-skr-pro-12",
	"firmwareBinaryName": "firmware-btt-skr-pro-12.bin",
	"compileScript": "compile.sh",
	"flashScript": "flash.sh",
	"driverCount": 6,
	"driverVoltages": [24],
	"flashInstructions": "Flashing only works if there's a properly formatted (FAT16 or FAT32 with a small blocksize) micro SD card in the SKR Pro's SD Card slot. The smaller the SD card the better, a cheap 128mb TF-card is perfect.",
	"documentationLink": "https://github.com/coolio986/ratical/docs/boards/btt/skr-pro-12",
	"ADXL345SPI": {
		"cs_pin": "PA15",
		"hardware": {
			"bus": "spi3a"
		}
	},
	"stepperSPI": {
		"software": {
			"sclk": "PC10",
			"mosi": "PC12",
			"miso": "PC11"
		}
	},
	"motorSlots": {
		"X": {
			"title": "X",
			"enable_pin": "PF2",
			"step_pin": "PE9",
			"dir_pin": "PF1",
			"uart_pin": "PC13",
			"cs_pin": "PC13",
			"diag_pin": "PB10",
			"endstop_pin": "PB10",
			"spi_software_mosi_pin": "PC12",
			"spi_software_miso_pin": "PC11",
			"spi_software_sclk_pin": "PC10"
		},
		"Y": {
			"title": "Y",
			"enable_pin": "PD7",
			"step_pin": "PE11",
			"dir_pin": "PE8",
			"uart_pin": "PE3",
			"cs_pin": "PE3",
			"diag_pin": "PE12",
			"endstop_pin": "PE12",
			"spi_software_mosi_pin": "PC12",
			"spi_software_miso_pin": "PC11",
			"spi_software_sclk_pin": "PC10"
		},
		"Z": {
			"title": "Z",
			"enable_pin": "PC0",
			"step_pin": "PE13",
			"dir_pin": "PC2",
			"uart_pin": "PE1",
			"cs_pin": "PE1",
			"diag_pin": "PG8",
			"endstop_pin": "PG8",
			"spi_software_mosi_pin": "PC12",
			"spi_software_miso_pin": "PC11",
			"spi_software_sclk_pin": "PC10"
		},
		"E0": {
			"title": "E0",
			"enable_pin": "PC3",
			"step_pin": "PE14",
			"dir_pin": "PA0",
			"uart_pin": "PD4",
			"cs_pin": "PD4",
			"diag_pin": "PE15",
			"endstop_pin": "PE15",
			"spi_software_mosi_pin": "PC12",
			"spi_software_miso_pin": "PC11",
			"spi_software_sclk_pin": "PC10"
		},
		"E1": {
			"title": "E1",
			"enable_pin": "PA3",
			"step_pin": "PD15",
			"dir_pin": "PE7",
			"uart_pin": "PD1",
			"cs_pin": "PD1",
			"diag_pin": "PE10",
			"endstop_pin": "PE10",
			"spi_software_mosi_pin": "PC12",
			"spi_software_miso_pin": "PC11",
			"spi_software_sclk_pin": "PC10"
		},
		"E2": {
			"title": "E2",
			"enable_pin": "PF0",
			"step_pin": "PD13",
			"dir_pin": "PG9",
			"uart_pin": "PD6",
			"cs_pin": "PD6",
			"diag_pin": "PG5",
			"endstop_pin": "PG5",
			"spi_software_mosi_pin": "PC12",
			"spi_software_miso_pin": "PC11",
			"spi_software_sclk_pin": "PC10"
		}
	}
}

=== coolio986/ratical/configuration/boards/btt-kraken/board-definition.json
{
	"$schema": "../board-definition.schema.json",
	"boardImageFileName": "board.webp",
	"manualFileName": "manual.pdf",
	"wireDiagramFileName": "wiring.drawio.svg",
	"name": "Kraken",
	"manufacturer": "BIGTREETECH",
	"id": "btt-kraken",
	"firmwareBinaryName": "firmware-btt-kraken.bin",
	"compileScript": "compile.sh",
	"flashScript": "flash.sh",
	"flashInstructions": "Flashing only works if the SD card slot on the Octopus is empty.",
	"documentationLink": "https://github.com/coolio986/ratical/docs/boards/btt/btt-kraken",
	"driverCount": 8,
	"driverVoltages": [24, 36, 48, 56],
	"fourPinFanConnectorCount": 2,
	"dfu": {
		"flashDevice": "0483:df11",
		"dfuBootImage": "dfubooting.drawio.png",
		"instructions": [
			"Connect the board via USB to the Raspberry Pi",
			"Make sure the board is powered (you can use usb power by placing a jumper on the VBUS pins)",
			"Press and hold the BOOT0 button on the board.",
			"Press and release the RESET button on the board.",
			"Release the BOOT0 button."
		],
		"hasBoot0Jumper": false
	},
	"ADXL345SPI": {
		"cs_pin": "PE10",
		"software": {
			"sclk": "PE12",
			"mosi": "PE14",
			"miso": "PE13"
		}
	},
	"stepperSPI": {
		"software": {
			"sclk": "PE12",
			"mosi": "PE14",
			"miso": "PE13"
		}
	},
	"integratedDrivers": {
		"MOTOR1": "BTT-KRAKEN-2160-PLUS",
		"MOTOR2": "BTT-KRAKEN-2160-PLUS",
		"MOTOR3": "BTT-KRAKEN-2160-PLUS",
		"MOTOR4": "BTT-KRAKEN-2160-PLUS",
		"MOTOR5": "BTT-KRAKEN-2160",
		"MOTOR6": "BTT-KRAKEN-2160",
		"MOTOR7": "BTT-KRAKEN-2160",
		"MOTOR8": "BTT-KRAKEN-2160"
	},
	"motorSlots": {
		"MOTOR1": {
			"title": "MOTOR 1",
			"enable_pin": "PE6",
			"step_pin": "PC14",
			"dir_pin": "PC13",
			"cs_pin": "PD6",
			"diag_pin": "PC15",
			"endstop_pin": "PC15",
			"spi_software_mosi_pin": "PC8",
			"spi_software_miso_pin": "PC7",
			"spi_software_sclk_pin": "PC6"
		},
		"MOTOR2": {
			"title": "MOTOR 2",
			"enable_pin": "PE3",
			"step_pin": "PE5",
			"dir_pin": "PE4",
			"cs_pin": "PD5",
			"diag_pin": "PF0",
			"endstop_pin": "PF0",
			"spi_software_mosi_pin": "PC8",
			"spi_software_miso_pin": "PC7",
			"spi_software_sclk_pin": "PC6"
		},
		"MOTOR3": {
			"title": "MOTOR 3",
			"enable_pin": "PE0",
			"step_pin": "PE2",
			"dir_pin": "PE1",
			"cs_pin": "PD4",
			"diag_pin": "PF1",
			"endstop_pin": "PF1",
			"spi_software_mosi_pin": "PC8",
			"spi_software_miso_pin": "PC7",
			"spi_software_sclk_pin": "PC6"
		},
		"MOTOR4": {
			"title": "MOTOR 4",
			"enable_pin": "PB7",
			"step_pin": "PB9",
			"dir_pin": "PB8",
			"cs_pin": "PD3",
			"diag_pin": "PF2",
			"endstop_pin": "PF2",
			"spi_software_mosi_pin": "PC8",
			"spi_software_miso_pin": "PC7",
			"spi_software_sclk_pin": "PC6"
		},
		"MOTOR5": {
			"title": "MOTOR 5",
			"enable_pin": "PG13",
			"step_pin": "PG9",
			"dir_pin": "PG10",
			"cs_pin": "PD2",
			"diag_pin": "PF3",
			"endstop_pin": "PF3",
			"spi_software_mosi_pin": "PC8",
			"spi_software_miso_pin": "PC7",
			"spi_software_sclk_pin": "PC6"
		},
		"MOTOR6": {
			"title": "MOTOR 6",
			"enable_pin": "PG12",
			"step_pin": "PG11",
			"dir_pin": "PD7",
			"cs_pin": "PA15",
			"diag_pin": "PF4",
			"endstop_pin": "PF4",
			"spi_software_mosi_pin": "PC8",
			"spi_software_miso_pin": "PC7",
			"spi_software_sclk_pin": "PC6"
		},
		"MOTOR7": {
			"title": "MOTOR 7",
			"enable_pin": "PB5",
			"step_pin": "PB4",
			"dir_pin": "PB3",
			"cs_pin": "PA9",
			"diag_pin": "PF10",
			"endstop_pin": "PF10",
			"spi_software_mosi_pin": "PC8",
			"spi_software_miso_pin": "PC7",
			"spi_software_sclk_pin": "PC6"
		},
		"MOTOR8": {
			"title": "MOTOR 8",
			"enable_pin": "PG14",
			"step_pin": "PG15",
			"dir_pin": "PB6",
			"cs_pin": "PA10",
			"diag_pin": "PC0",
			"endstop_pin": "PC0",
			"spi_software_mosi_pin": "PC8",
			"spi_software_miso_pin": "PC7",
			"spi_software_sclk_pin": "PC6"
		}
	}
}
