=== coolio986/ratical/configuration/boards/board-definition.schema.json
{
	"$schema": "https://json-schema.org/draft-07/schema",
	"$id": "https://github.com/coolio986/ratical/board-definition.schema.json",
	"title": "Control Board",
	"description": "A 3d printer control board",
	"type": "object",
	"additionalProperties": false,
	"properties": {
		"$schema": { "type": "string" },
		"id": {
			"description": "The path for serial communication with this MCU",
			"type": "string"
		},
		"name": {
			"description": "The name of the control board",
			"type": "string"
		},
		"manufacturer": {
			"description": "The name of the manufacturer of this board",
			"type": "string"
		},
		"firmwareBinaryName": {
			"description": "The firmware binary filename in Ratical",
			"type": "string"
		},
		"compileScript": {
			"description": "The path to the compilation script if the board supports automatic firmware compilation, relative to the board definition directory",
			"type": "string"
		},
		"flashScript": {
			"description": "The path to the flashing script if the board supports automatic firmware flashing, relative to the board definition directory",
			"type": "string"
		},
		"flashInstructions": {
			"description": "Instructions for how to make sure the board can be automatically flashed",
			"type": "string"
		},
		"documentationLink": {
			"description": "Link to the Ratical configuration for this board",
			"type": "string"
		},
		"manualFileName": {
			"description": "The filename of the manual for this board, should be placed in the board directory.",
			"type": "string"
		},
		"wireDiagramFileName": {
			"description": "The filename of the wire diagram for this board, should be placed in the board directory.",
			"type": "string"
		},
		"boardImageFileName": {
			"description": "The filename of the image of this board, should be placed in the board directory.",
			"type": "string"
		},
		"isToolboard": {
			"description": "Whether this controlboard is a toolboard",
			"type": "boolean"
		},
		"isHost": {
			"description": "Whether this is the host computer Ratical is running on (used for Pi)",
			"type": "boolean"
		},
		"serialPath": {
			"description": "This property is only required for host boards. It is the path to the serial port to use for communication with the host mcu",
			"type": "string"
		},
		"disableAutoFlash": {
			"description": "Whether to disable automatic flashing of this board",
			"type": "boolean"
		},
		"firmwareOptions": {
			"description": "Advanced Kalico menuconfig symbols (without the CONFIG_ prefix) to expose as opt-in firmware options during flashing. Availability, labels and help text are resolved from the installed Kalico branch's Kconfig at query time; symbols whose dependencies are not met for this board are hidden.",
			"type": "array",
			"items": {
				"type": "string"
			}
		},
		"hasQuirksFiles": {
			"description": "Whether this board has a quirks file that needs to be loaded (must be called quirks.cfg and quirks-toolboard.cfg)",
			"type": "boolean"
		},
		"alternativePT1000Resistor": {
			"description": "The value of an optional resistor used for PT1000 sensors, if different from the default 4700",
			"type": "number"
		},
		"thermistorPullup": {
			"description": "The value of the pullup resistor used for thermistors, if different from the default 4700",
			"type": "number"
		},
		"driverCount": {
			"description": "How many drivers this board has",
			"type": "number"
		},
		"hasMcuTempSensor": {
			"description": "Whether this board has an MCU temperature sensor, default is true",
			"type": "boolean"
		},
		"outputPins": {
			"description": "Output pin definitions. Some boards have safety features that require a pin to be pulled high to enable power, such as the SKR2.",
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"name": {
						"description": "The name of the feature",
						"type": "string"
					},
					"pin": {
						"type": "string"
					},
					"value": {
						"type": "number",
						"maximum": 1,
						"minimum": 0
					},
					"shutdownValue": {
						"type": "number",
						"maximum": 1,
						"minimum": 0
					}
				}
			}
		},
		"customSections": {
			"description": "Custom sections for this board",
			"type": "object",
			"additionalProperties": false,
			"patternProperties": {
				"^\\S+$": {
					"type": "object",
					"properties": {
						"name": {
							"description": "The name of the custom section",
							"type": "string"
						},
						"isPerToolhead": {
							"description": "Whether custom section is per toolhead. Default is true. If true, `name` must be specified. If there is more than one toolhead, the toolhead index will be appended to the name in the generated config like `name_t0`, `name_t1`, etc. Note that there is currently no way for a per-toolhead custom section to have different parameters per toolhead, including referencing another per-toolhead section. Pin references will be automatically adjusted per-toolhead index. If `isPerToolhead` is false, the custom section is global, and must not contain pin references.",
							"type": "boolean"
						},
						"parameters": {
							"description": "The parameters for this custom section",
							"type": "object",
							"additionalProperties": false,
							"patternProperties": {
								"^\\S+$": {
									"description": "A parameter and value for this custom section",
									"oneOf": [{ "type": "number" }, { "type": "string" }, { "type": "boolean" }]
								}
							}
						},
						"comments": {
							"description": "Comments for this custom section",
							"type": "array",
							"items": {
								"type": "string"
							}
						}
					},
					"required": ["parameters"]
				}
			}
		},
		"invertPinLogic": {
			"description": "A list of pins to invert the logic of",
			"type": "array",
			"items": {
				"type": "string"
			}
		},
		"motorSlots": {
			"description": "A specification of the motor slots available on this board",
			"type": "object",
			"patternProperties": {
				"^\\S+$": {
					"type": "object",
					"description": "The settings for a motor slot",
					"properties": {
						"title": {
							"type": "string"
						},
						"step_pin": {
							"type": "string"
						},
						"dir_pin": {
							"type": "string"
						},
						"enable_pin": {
							"type": "string"
						},
						"diag_pin": {
							"type": "string"
						},
						"endstop_pin": {
							"type": "string"
						},
						"uart_pin": {
							"type": "string"
						},
						"uart_address": {
							"type": "string"
						},
						"rx_pin": {
							"type": "string"
						},
						"tx_pin": {
							"type": "string"
						},
						"cs_pin": {
							"type": "string"
						},
						"spi_bus": {
							"type": "string"
						},
						"spi_software_mosi_pin": {
							"type": "string"
						},
						"spi_software_miso_pin": {
							"type": "string"
						},
						"spi_software_sclk_pin": {
							"type": "string"
						}
					},
					"additionalProperties": false,
					"required": ["step_pin", "dir_pin", "enable_pin", "title", "uart_pin", "cs_pin"]
				}
			}
		},
		"stepperSPI": {
			"description": "Which settings to use for SPI stepper drivers",
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"software": {
					"description": "Whether to use software SPI",
					"type": "object",
					"additionalProperties": false,
					"required": ["sclk", "mosi", "miso"],
					"properties": {
						"sclk": {
							"description": "The clock pin",
							"type": "string"
						},
						"mosi": {
							"description": "The mosi pin",
							"type": "string"
						},
						"miso": {
							"description": "The miso pin",
							"type": "string"
						}
					}
				},
				"hardware": {
					"description": "Which SPI bus to use if using hardware spi",
					"type": "object",
					"required": ["bus"],
					"additionalProperties": false,
					"properties": {
						"bus": {
							"description": "The SPI bus to use",
							"type": "string"
						}
					}
				}
			}
		},
		"hotendHeater": {
			"description": "Board-specific settings to use for the hotend heater",
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"maxPower": {
					"description": "The maximum power for the hotend heater",
					"type": "object",
					"additionalProperties": false,
					"properties": {
						"value": { "description": "Max power (0.0-1.0)", "type": "number" },
						"comment": { "description": "Optional comment to include in generated config", "type": "string" }
					},
					"required": ["value"]
				},
				"pwmCycleTime": {
					"description": "The PWM cycle time for the hotend heater",
					"type": "object",
					"additionalProperties": false,
					"properties": {
						"value": { "description": "The PWM cycle time (seconds)", "type": "number" },
						"comment": { "description": "Optional comment to include in generated config", "type": "string" }
					},
					"required": ["value"]
				}
			}
		},
		"partCoolingFan": {
			"description": "Board-specific settings to use for part cooling fan control",
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"maxPower": {
					"description": "The maximum power for the part cooling fan",
					"type": "object",
					"additionalProperties": false,
					"properties": {
						"value": { "description": "Max power (0.0-1.0)", "type": "number" },
						"comment": { "description": "Optional comment to include in generated config", "type": "string" }
					},
					"required": ["value"]
				},
				"inputVoltagePwmCycleTime": {
					"description": "The PWM cycle time for part cooling fan control when using input voltage control (e.g. 2-pin and 3-pin fans).",
					"type": "object",
					"additionalProperties": false,
					"properties": {
						"value": { "description": "The cycle time value (seconds)", "type": "number" },
						"comment": { "description": "Optional comment to include in generated config", "type": "string" }
					},
					"required": ["value"]
				}
			}
		},
		"toolheadCoolingFan": {
			"description": "Board-specific settings to use for toolhead cooling fan control",
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"maxPower": {
					"description": "The maximum power for the toolhead cooling fan",
					"type": "object",
					"additionalProperties": false,
					"properties": {
						"value": { "description": "Max power (0.0-1.0)", "type": "number" },
						"comment": { "description": "Optional comment to include in generated config", "type": "string" }
					},
					"required": ["value"]
				},
				"inputVoltagePwmCycleTime": {
					"description": "The PWM cycle time for toolhead cooling fan control when using input voltage control (e.g. 2-pin and 3-pin fans)",
					"type": "object",
					"additionalProperties": false,
					"properties": {
						"value": { "description": "The cycle time value (seconds)", "type": "number" },
						"comment": { "description": "Optional comment to include in generated config", "type": "string" }
					},
					"required": ["value"]
				}
			}
		},
		"ADXL345SPI": {
			"description": "Which settings to use for the ADXL345 accelerometer",
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"software": {
					"description": "Whether to use software SPI",
					"type": "object",

					"additionalProperties": false,
					"properties": {
						"sclk": {
							"description": "The clock pin",
							"type": "string"
						},
						"mosi": {
							"description": "The mosi pin",
							"type": "string"
						},
						"miso": {
							"description": "The miso pin",
							"type": "string"
						}
					}
				},
				"hardware": {
					"description": "Which SPI bus to use if using hardware spi",
					"type": "object",
					"additionalProperties": false,
					"properties": {
						"bus": {
							"description": "The SPI bus to use",
							"type": "string"
						}
					}
				},
				"cs_pin": {
					"description": "The chip select pin",
					"type": "string"
				},
				"axesMap": {
					"description": "Optional axes mapping for the accelerometer. Default is 'x, z, y'",
					"type": "string"
				}
			}
		},
		"LIS2DW": {
			"description": "Which settings to use for the ADXL345 accelerometer",
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"software": {
					"description": "Whether to use software SPI",
					"type": "object",

					"additionalProperties": false,
					"properties": {
						"sclk": {
							"description": "The clock pin",
							"type": "string"
						},
						"mosi": {
							"description": "The mosi pin",
							"type": "string"
						},
						"miso": {
							"description": "The miso pin",
							"type": "string"
						}
					}
				},
				"hardware": {
					"description": "Which SPI bus to use if using hardware spi",
					"type": "object",
					"additionalProperties": false,
					"properties": {
						"bus": {
							"description": "The SPI bus to use",
							"type": "string"
						}
					}
				},
				"cs_pin": {
					"description": "The chip select pin",
					"type": "string"
				},
				"axesMap": {
					"description": "Optional axes mapping for the accelerometer. Default is 'x, z, y'",
					"type": "string"
				}
			}
		},
		"integratedDrivers": {
			"description": "Describes the drivers integrated on this board, if any",
			"type": "object",
			"additionalProperties": true,
			"properties": {
				"x": {
					"description": "The driver for the X axis",
					"type": "string"
				},
				"y": {
					"description": "The driver for the Y axis",
					"type": "string"
				},
				"z": {
					"description": "The driver for the Z axis",
					"type": "string"
				},
				"z1": {
					"description": "The driver for the Z axis",
					"type": "string"
				},
				"z2": {
					"description": "The driver for the Z axis",
					"type": "string"
				},
				"extruder": {
					"description": "The driver for the E axis",
					"type": "string"
				}
			}
		},
		"driverVoltages": {
			"description": "The supported stepper voltages. 24, 36, 48, 56 and 60 is supported. Default is 24 only.",
			"type": "array",
			"items": {
				"type": "number"
			}
		},
		"extruderlessConfig": {
			"description": "The name of an extruderless config (used for 5 driver boards to support 6 driver printers)",
			"type": "string"
		},
		"fourPinFanConnectorCount": {
			"description": "How many 4 pin fan connectors this board has",
			"type": "number"
		},
		"dfu": {
			"description": "DFU Flashing details",
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"dfuBootImage": {
					"description": "Path to a picture for locating the buttons and/or jumpers required to boot into DFU mode",
					"type": "string"
				},
				"flashDevice": {
					"description": "A string containing the vendor and device id to use as the flash target, eg 0483:df11",
					"type": "string"
				},
				"instructions": {
					"description": "Instruction steps for how to boot into DFU mode",
					"type": "array",
					"items": {
						"type": "string"
					}
				},
				"reminder": {
					"description": "Post-flashing reminders, if any.",
					"type": "string"
				},
				"hasBoot0Jumper": {
					"description": "Whether this board has a boot0 jumper",
					"type": "boolean"
				}
			},
			"required": ["dfuBootImage", "flashDevice", "instructions", "hasBoot0Jumper"]
		},
		"sdFileName": {
			"description": "The filename for the firmware binary when flashing via SD card",
			"type": "string"
		}
	},
	"required": ["id", "name", "manufacturer", "firmwareBinaryName", "compileScript", "documentationLink", "driverCount"]
}

=== coolio986/ratical/configuration/boards/btt-octopus-pro-446/board-definition.json
{
	"$schema": "../board-definition.schema.json",
	"boardImageFileName": "board.webp",
	"manualFileName": "manual.pdf",
	"wireDiagramFileName": "wiring.drawio.svg",
	"name": "Octopus Pro 446",
	"manufacturer": "BIGTREETECH",
	"id": "btt-octopus-pro-446",
	"firmwareBinaryName": "firmware-btt-octopus-pro-446.bin",
	"compileScript": "compile.sh",
	"flashScript": "flash.sh",
	"flashInstructions": "Flashing only works if the SD card slot on the Octopus Pro is empty.",
	"documentationLink": "https://github.com/coolio986/ratical/docs/boards/btt/octopus-pro-446",
	"driverCount": 8,
	"driverVoltages": [24, 36, 48, 56],
	"dfu": {
		"flashDevice": "0483:df11",
		"dfuBootImage": "dfubooting.drawio.png",
		"instructions": [
			"Connect the board via USB to the Raspberry Pi",
			"Add the jumper to BOOT0 as shown in the picture",
			"Make sure the board is powered on",
			"If the board was already connected and powered when you inserted the jumper, click the reset button on the board."
		],
		"hasBoot0Jumper": true
	},
	"motorSlots": {
		"MOTOR0": {
			"title": "MOTOR 0",
			"enable_pin": "PF14",
			"step_pin": "PF13",
			"dir_pin": "PF12",
			"uart_pin": "PC4",
			"cs_pin": "PC4",
			"diag_pin": "PG6",
			"endstop_pin": "PG6",
			"spi_software_mosi_pin": "PA7",
			"spi_software_miso_pin": "PA6",
			"spi_software_sclk_pin": "PA5"
		},
		"MOTOR1": {
			"title": "MOTOR 1",
			"enable_pin": "PF15",
			"step_pin": "PG0",
			"dir_pin": "PG1",
			"uart_pin": "PD11",
			"cs_pin": "PD11",
			"diag_pin": "PG9",
			"endstop_pin": "PG9",
			"spi_software_mosi_pin": "PA7",
			"spi_software_miso_pin": "PA6",
			"spi_software_sclk_pin": "PA5"
		},
		"MOTOR2": {
			"title": "MOTOR 2",
			"enable_pin": "PG5",
			"step_pin": "PF11",
			"dir_pin": "PG3",
			"uart_pin": "PC6",
			"cs_pin": "PC6",
			"diag_pin": "PG10",
			"endstop_pin": "PG10",
			"spi_software_mosi_pin": "PA7",
			"spi_software_miso_pin": "PA6",
			"spi_software_sclk_pin": "PA5"
		},
		"MOTOR3": {
			"title": "MOTOR 3",
			"enable_pin": "PA0",
			"step_pin": "PG4",
			"dir_pin": "PC1",
			"uart_pin": "PC7",
			"cs_pin": "PC7",
			"diag_pin": "PG11",
			"endstop_pin": "PG11",
			"spi_software_mosi_pin": "PA7",
			"spi_software_miso_pin": "PA6",
			"spi_software_sclk_pin": "PA5"
		},
		"MOTOR4": {
			"title": "MOTOR 4",
			"enable_pin": "PG2",
			"step_pin": "PF9",
			"dir_pin": "PF10",
			"uart_pin": "PF2",
			"cs_pin": "PF2",
			"diag_pin": "PG12",
			"endstop_pin": "PG12",
			"spi_software_mosi_pin": "PA7",
			"spi_software_miso_pin": "PA6",
			"spi_software_sclk_pin": "PA5"
		},
		"MOTOR5": {
			"title": "MOTOR 5",
			"enable_pin": "PF1",
			"step_pin": "PC13",
			"dir_pin": "PF0",
			"uart_pin": "PE4",
			"cs_pin": "PE4",
			"diag_pin": "PG13",
			"endstop_pin": "PG13",
			"spi_software_mosi_pin": "PA7",
			"spi_software_miso_pin": "PA6",
			"spi_software_sclk_pin": "PA5"
		},
		"MOTOR6": {
			"title": "MOTOR 6",
			"enable_pin": "PD4",
			"step_pin": "PE2",
			"dir_pin": "PE3",
			"uart_pin": "PE1",
			"cs_pin": "PE1",
			"diag_pin": "PG14",
			"endstop_pin": "PG14",
			"spi_software_mosi_pin": "PA7",
			"spi_software_miso_pin": "PA6",
			"spi_software_sclk_pin": "PA5"
		},
		"MOTOR7": {
			"title": "MOTOR 7",
			"enable_pin": "PE0",
			"step_pin": "PE6",
			"dir_pin": "PA14",
			"uart_pin": "PD3",
			"cs_pin": "PD3",
			"diag_pin": "PG15",
			"endstop_pin": "PG15",
			"spi_software_mosi_pin": "PA7",
			"spi_software_miso_pin": "PA6",
			"spi_software_sclk_pin": "PA5"
		}
	},
	"ADXL345SPI": {
		"cs_pin": "PA15",
		"hardware": {
			"bus": "spi3"
		}
	},
	"stepperSPI": {
		"software": {
			"sclk": "PA5",
			"mosi": "PA7",
			"miso": "PA6"
		}
	}
}

=== coolio986/ratical/configuration/boards/btt-skr-2-407/board-definition.json
{
	"$schema": "../board-definition.schema.json",
	"boardImageFileName": "board.png",
	"manualFileName": "manual.pdf",
	"wireDiagramFileName": "wiring.drawio.svg",
	"name": "SKR 2 407",
	"manufacturer": "BIGTREETECH",
	"id": "btt-skr-2-407",
	"firmwareBinaryName": "firmware-btt-skr-2-407.bin",
	"driverCount": 5,
	"driverVoltages": [24],
	"compileScript": "compile.sh",
	"documentationLink": "https://github.com/coolio986/ratical/docs/boards/btt/skr-2-429",
	"outputPins": [
		{
			"name": "Motor_Power",
			"pin": "PC13",
			"value": 1
		}
	],
	"ADXL345SPI": {
		"cs_pin": "PB12",
		"hardware": {
			"bus": "spi2"
		}
	},
	"stepperSPI": {
		"software": {
			"sclk": "PE15",
			"mosi": "PE14",
			"miso": "PA14"
		}
	},
	"motorSlots": {
		"X": {
			"title": "X",
			"enable_pin": "PE3",
			"step_pin": "PE2",
			"dir_pin": "PE1",
			"uart_pin": "PE0",
			"cs_pin": "PE0",
			"diag_pin": "PC1",
			"endstop_pin": "PC1",
			"spi_software_mosi_pin": "PE14",
			"spi_software_miso_pin": "PA14",
			"spi_software_sclk_pin": "PE15"
		},
		"Y": {
			"title": "Y",
			"enable_pin": "PD6",
			"step_pin": "PD5",
			"dir_pin": "PD4",
			"uart_pin": "PD3",
			"cs_pin": "PD3",
			"diag_pin": "PC3",
			"endstop_pin": "PC3",
			"spi_software_mosi_pin": "PE14",
			"spi_software_miso_pin": "PA14",
			"spi_software_sclk_pin": "PE15"
		},
		"Z": {
			"title": "Z",
			"enable_pin": "PD1",
			"step_pin": "PA15",
			"dir_pin": "PA8",
			"uart_pin": "PD0",
			"cs_pin": "PD0",
			"diag_pin": "PC0",
			"endstop_pin": "PC0",
			"spi_software_mosi_pin": "PE14",
			"spi_software_miso_pin": "PA14",
			"spi_software_sclk_pin": "PE15"
		},
		"E0": {
			"title": "E0",
			"enable_pin": "PC7",
			"step_pin": "PD15",
			"dir_pin": "PD14",
			"uart_pin": "PC6",
			"cs_pin": "PC6",
			"diag_pin": "PC2",
			"endstop_pin": "PC2",
			"spi_software_mosi_pin": "PE14",
			"spi_software_miso_pin": "PA14",
			"spi_software_sclk_pin": "PE15"
		},
		"E1": {
			"title": "E1",
			"enable_pin": "PD13",
			"step_pin": "PD11",
			"dir_pin": "PD10",
			"uart_pin": "PD12",
			"cs_pin": "PD12",
			"diag_pin": "PA0",
			"endstop_pin": "PA0",
			"spi_software_mosi_pin": "PE14",
			"spi_software_miso_pin": "PA14",
			"spi_software_sclk_pin": "PE15"
		}
	}
}

=== coolio986/ratical/configuration/boards/mellow-fly-sht-36/board-definition.json
{
	"$schema": "../board-definition.schema.json",
	"boardImageFileName": "board.webp",
	"wireDiagramFileName": "wiring.drawio.svg",
	"isToolboard": true,
	"name": "FLY-SHT36",
	"manufacturer": "Mellow",
	"id": "mellow-fly-sht-36",
	"firmwareBinaryName": "firmware-mellow-fly-sht-36.bin",
	"compileScript": "compile.sh",
	"flashScript": "flash.sh",
	"flashInstructions": "After initial flashing, make sure the boot0 jumper is not inserted.",
	"documentationLink": "https://github.com/coolio986/ratical/docs/boards/mellow/fly-sht-36",
	"thermistorPullup": 2200,
	"driverCount": 1,
	"integratedDrivers": {
		"extruder": "MELLOW-FLY-TMC2209"
	},
	"dfu": {
		"flashDevice": "0483:df11",
		"dfuBootImage": "dfubooting.png",
		"instructions": [
			"Add the jumper as shown in the picture",
			"Connect the board via USB to the Raspberry Pi",
			"Make sure the board is powered on",
			"If the board was already connected and powered when you inserted the jumper, click the boot button on the board."
		],
		"hasBoot0Jumper": true
	},
	"ADXL345SPI": {
		"cs_pin": "PA4",
		"hardware": {
			"bus": "spi1"
		}
	}
}

=== coolio986/ratical/configuration/boards/ldo-orbitool-o2/board-definition.json
{
	"$schema": "../board-definition.schema.json",
	"isToolboard": true,
	"name": "Orbitool O2",
	"manufacturer": "LDO",
	"id": "ldo-orbitool-o2",
	"firmwareBinaryName": "firmware-ldo-orbitool-o2.bin",
	"boardImageFileName": "board.webp",
	"compileScript": "compile.sh",
	"thermistorPullup": 2200,
	"flashScript": "flash.sh",
	"documentationLink": "https://github.com/coolio986/ratical/docs/boards/ldo/orbitool-o2",
	"disableAutoFlash": true,
	"driverVoltages": [24],
	"hasMcuTempSensor": true,
	"invertPinLogic": ["PA9"],
	"driverCount": 1,
	"integratedDrivers": {
		"extruder": "LDO-TMC2209"
	},
	"dfu": {
		"flashDevice": "0483:df11",
		"dfuBootImage": "dfubooting.webp",
		"instructions": [
			"Connect the board via USB to the Raspberry Pi",
			"Make sure the board is powered (you can use usb power by placing a jumper on the VBUS pins)",
			"Press and hold the BOOT button on the board.",
			"Press and release the RESET button on the board.",
			"Release the BOOT button."
		],
		"hasBoot0Jumper": false
	},
	"outputPins": [
		{
			"name": "_run_led",
			"pin": "PB8",
			"value": 1
		}
	],
	"hotendHeater": {
		"maxPower": { 
			"value": 0.995,
		    "comment": "The hotend heater power must be limited to 99.5% (max_power: 0.995) to enable the correct operation of Orbitool O2s protection features. Do not set max_power to a value greater than 0.995."
		},
		"pwmCycleTime": {
			"value": 0.01,
			"comment": "To improve the heater power calculation accuracy, the heater PWM is forced to 100Hz (instead of the 10Hz default of Klipper)."
		}
	},
	"partCoolingFan": {
		"inputVoltagePwmCycleTime": {
			"value": 0.02,
			"comment": "cycle_time as per Orbitool O2 example config"
		},
		"maxPower": { 
			"value": 0.995, 
			"comment": "The part fan power must be limited to 99.5% (max_power: 0.995) to enable the correct operation of Orbitool O2s protection features. Do not set max_power to a value greater than 0.995."
		}
	},
	"toolheadCoolingFan": {
		"maxPower": { 
			"value": 1,
			"comment": "Use max_power: 0.5 for 12V, max_power: 1 for 24V (in printer.cfg)" 
		},
		"inputVoltagePwmCycleTime": { 
			"value": 0.0001,
			"comment": "The Orbitool O2s DC-DC fan control circuit is designed for a command signal of 10khz. Do not change."
		}
	},
	"LIS2DW": {
		"cs_pin": "PA4",
		"hardware": {
			"bus": "spi1"
		},
		"axesMap": "y, z, x"
	},
	"customSections": {
		"adc_temperature": {
			"name": "orbitool_o2_hotend_power_scale",
			"isPerToolhead": false,
			"parameters": {
				"temperature1": 119,
				"voltage1": 1.91,
				"temperature2": 239,
				"voltage2": 3.82
			}
		},
	"temperature_sensor": {
			"name": "hotend_power",
			"parameters": {
				"sensor_pin": "PA2",
				"sensor_type": "orbitool_o2_hotend_power_scale"
			}
		}
	}
}

=== coolio986/ratical/configuration/boards/btt-manta-m8p-20/board-definition.json
{
	"$schema": "../board-definition.schema.json",
	"boardImageFileName": "board.webp",
	"manualFileName": "manual.pdf",
	"wireDiagramFileName": "wiring.drawio.svg",
	"name": "Manta M8P v2.0",
	"manufacturer": "BIGTREETECH",
	"id": "btt-manta-m8p-20",
	"firmwareBinaryName": "firmware-btt-manta-m8p-20.bin",
	"compileScript": "compile.sh",
	"flashScript": "flash.sh",
	"documentationLink": "https://github.com/coolio986/ratical/docs/boards/btt/manta-m8p-11",
	"fourPinFanConnectorCount": 2,
	"driverCount": 8,
	"driverVoltages": [24, 36, 48, 56],
	"dfu": {
		"flashDevice": "0483:df11",
		"dfuBootImage": "dfubooting.drawio.png",
		"instructions": [
			"Make sure the board is powered on",
			"Press and hold the BOOT 0 button on the board.",
			"Press and release the RESET button on the board.",
			"Release the BOOT 0 button."
		],
		"hasBoot0Jumper": false
	},
	"motorSlots": {
		"MOTOR1": {
			"title": "MOTOR 1",
			"enable_pin": "PC14",
			"step_pin": "PE6",
			"dir_pin": "PE5",
			"uart_pin": "PC13",
			"cs_pin": "PC13",
			"diag_pin": "PF4",
			"endstop_pin": "PF4",
			"spi_software_mosi_pin": "PG6",
			"spi_software_miso_pin": "PG7",
			"spi_software_sclk_pin": "PG8"
		},
		"MOTOR2": {
			"title": "MOTOR 2",
			"enable_pin": "PE4",
			"step_pin": "PE2",
			"dir_pin": "PE1",
			"uart_pin": "PE3",
			"cs_pin": "PE3",
			"diag_pin": "PF3",
			"endstop_pin": "PF3",
			"spi_software_mosi_pin": "PG6",
			"spi_software_miso_pin": "PG7",
			"spi_software_sclk_pin": "PG8"
		},
		"MOTOR3": {
			"title": "MOTOR 3",
			"enable_pin": "PE0",
			"step_pin": "PB8",
			"dir_pin": "PB7",
			"uart_pin": "PB9",
			"cs_pin": "PB9",
			"diag_pin": "PF2",
			"endstop_pin": "PF2",
			"spi_software_mosi_pin": "PG6",
			"spi_software_miso_pin": "PG7",
			"spi_software_sclk_pin": "PG8"
		},
		"MOTOR4": {
			"title": "MOTOR 4",
			"enable_pin": "PB6",
			"step_pin": "PB4",
			"dir_pin": "PB3",
			"uart_pin": "PB5",
			"cs_pin": "PB5",
			"diag_pin": "PF1",
			"endstop_pin": "PF1",
			"spi_software_mosi_pin": "PG6",
			"spi_software_miso_pin": "PG7",
			"spi_software_sclk_pin": "PG8"
		},
		"MOTOR5": {
			"title": "MOTOR 5",
			"enable_pin": "PG15",
			"step_pin": "PG13",
			"dir_pin": "PG12",
			"uart_pin": "PG14",
			"cs_pin": "PG14",
			"diag_pin": "PF0",
			"endstop_pin": "PF0",
			"spi_software_mosi_pin": "PG6",
			"spi_software_miso_pin": "PG7",
			"spi_software_sclk_pin": "PG8"
		},
		"MOTOR6": {
			"title": "MOTOR 6",
			"enable_pin": "PG11",
			"step_pin": "PG9",
			"dir_pin": "PD7",
			"uart_pin": "PG10",
			"cs_pin": "PG10",
			"diag_pin": "PC15",
			"endstop_pin": "PC15",
			"spi_software_mosi_pin": "PG6",
			"spi_software_miso_pin": "PG7",
			"spi_software_sclk_pin": "PG8"
		},
		"MOTOR7": {
			"title": "MOTOR 7",
			"enable_pin": "PD6",
			"step_pin": "PD4",
			"dir_pin": "PD3",
			"uart_pin": "PD5",
			"cs_pin": "PD5",
			"spi_software_mosi_pin": "PG6",
			"spi_software_miso_pin": "PG7",
			"spi_software_sclk_pin": "PG8"
		},
		"MOTOR8": {
			"title": "MOTOR 8",
			"enable_pin": "PD2",
			"step_pin": "PC7",
			"dir_pin": "PC8",
			"uart_pin": "PC6",
			"cs_pin": "PC6",
			"spi_software_mosi_pin": "PG6",
			"spi_software_miso_pin": "PG7",
			"spi_software_sclk_pin": "PG8"
		}
	},
	"ADXL345SPI": {
		"cs_pin": "PB12",
		"software": {
			"sclk": "PC10",
			"mosi": "PC12",
			"miso": "PC11"
		}
	},
	"stepperSPI": {
		"software": {
			"sclk": "PG8",
			"mosi": "PG6",
			"miso": "PG7"
		}
	}
}
