=== coolio986/ratical/configuration/printers/printer-definition.schema.json
{
	"$schema": "https://json-schema.org/draft-07/schema",
	"$id": "https://github.com/coolio986/ratical/printer-definition.schema.json",
	"title": "Printer",
	"description": "A Ratical supported 3d printer",
	"type": "object",
	"additionalProperties": false,
	"properties": {
		"$schema": {
			"description": "The schema used for this file",
			"type": "string"
		},
		"name": {
			"description": "The name of the printer",
			"type": "string"
		},
		"description": {
			"description": "A description of the printer",
			"type": "string"
		},
		"manufacturer": {
			"description": "The name of the manufacturer of this printer",
			"type": "string"
		},
		"releaseDate": {
			"description": "The release date of this printer in ISO 8601/RFC3339 eg. 2023-12-31",
			"type": "string",
			"format": "date"
		},
		"documentationLink": {
			"description": "Link to the Ratical documentation for this printer",
			"type": "string"
		},
		"image": {
			"description": "Link to an image of the printer",
			"type": "string"
		},
		"driverCountRequired": {
			"description": "Amount of drivers required for this printer",
			"type": "number"
		},
		"kinematics": {
			"description": "Kinematics for this printer",
			"type": "string",
			"enum": ["hybrid-corexy", "hybrid-corexy-idex", "corexy", "cartesian"]
		},
		"bedMargin": {
			"description": "Margin around the bed in mm that is reachable by the toolhead, but not printable",
			"type": "object",
			"properties": {
				"x": {
					"description": "X margin in mm eg [0, 55], for 0 at the left and 55 at the right",
					"type": "array"
				},
				"y": {
					"description": "Y margin in mm eg [0, 55], for 0 at the front and 55 at the back",
					"type": "array",
					"items": {
						"type": "number"
					}
				}
			},
			"required": ["x", "y"],
			"additionalProperties": false
		},
		"sizes": {
			"description": "Size options for this printer",
			"type": "object",
			"patternProperties": {
				"^\\S+$": {
					"type": "object",
					"additionalProperties": false,
					"properties": {
						"x": {
							"type": "number"
						},
						"y": {
							"type": "number"
						},
						"z": {
							"type": "number"
						}
					},
					"required": ["x", "y", "z"]
				}
			}
		},
		"template": {
			"description": "Printer.cfg template for this printer",
			"type": "string"
		},
		"rails": {
			"description": "Rails (steppers/drivers) needed for this printer, can be 'x', 'x1', 'dual_carriage', 'y', 'y1', 'z', 'z1', 'z2', 'z3', 'extruder', 'extruder1'.",
			"type": "array",
			"items": {
				"type": "string"
			}
		},
		"speedLimits": {
			"type": "object",
			"additionalProperties": false,
			"description": "Speed limits for this printer",
			"properties": {
				"basic": {
					"type": "object",
					"additionalProperties": false,
					"description": "Standard speed limits",
					"properties": {
						"velocity": {
							"type": "number"
						},
						"accel": {
							"type": "number"
						},
						"z_velocity": {
							"type": "number"
						},
						"z_accel": {
							"type": "number"
						},
						"square_corner_velocity": {
							"type": "number"
						},
						"travel_velocity": {
							"type": "number"
						},
						"travel_accel": {
							"type": "number"
						}
					},
					"required": ["velocity", "accel", "z_velocity", "z_accel"]
				},
				"performance": {
					"type": "object",
					"additionalProperties": false,
					"description": "Performance speed limits",
					"properties": {
						"velocity": {
							"type": "number"
						},
						"accel": {
							"type": "number"
						},
						"z_velocity": {
							"type": "number"
						},
						"z_accel": {
							"type": "number"
						},
						"square_corner_velocity": {
							"type": "number"
						},
						"travel_velocity": {
							"type": "number"
						},
						"travel_accel": {
							"type": "number"
						}
					},
					"required": ["velocity", "accel", "z_velocity", "z_accel"]
				}
			},
			"required": ["basic"]
		},
		"defaults": {
			"description": "Default hardware for this printer",
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"toolheads": {
					"type": "array",
					"description": "Default toolheads for this printer",
					"items": {
						"type": "object",
						"additionalProperties": false,
						"properties": {
							"axis": {
								"description": "Motion axis for this toolhead.",
								"type": "string",
								"enum": ["x", "dual_carriage"]
							},
							"description": {
								"description": "Description of the toolhead such as where it's located on the printer",
								"type": "string"
							},
							"hotend": {
								"description": "Default hotend for this toolhead. Should be the name of the config without the file extension.",
								"type": "string"
							},
							"probe": {
								"description": "Default probe for this toolhead. Should be the name of the config without the file extension.",
								"type": "string"
							},
							"partFan": {
								"description": "Default part fan for this toolhead.",
								"type": "string",
								"enum": [
									"2pin",
									"4pin",
									"4pin-dedicated",
									"2pin-toolboard",
									"4pin-toolboard",
									"4pin-dedicated-toolboard"
								]
							},
							"hotendFan": {
								"description": "Default hotend fan for this toolhead.",
								"type": "string",
								"enum": [
									"2pin",
									"4pin",
									"4pin-dedicated",
									"2pin-toolboard",
									"4pin-toolboard",
									"4pin-dedicated-toolboard"
								]
							},
							"xEndstop": {
								"description": "Default x endstop for this toolhead",
								"type": "string",
								"enum": ["sensorless", "endstop", "endstop-toolboard"]
							},
							"yEndstop": {
								"description": "Default y endstop for this toolhead",
								"type": "string",
								"enum": ["sensorless", "endstop"]
							},
							"extruder": {
								"description": "Default extruder for this toolhead. Should be the name of the config without the file extension.",
								"type": "string"
							},
							"toolboard": {
								"description": "Default board for this toolhead. Should be the name of the board directory.",
								"type": "string"
							},
							"filamentSensor": {
								"description": "Default filament sensor for this toolhead. Should be the name of the /configuration/filament-sensors/* subdir.",
								"type": "object",
								"properties": {
									"id": {
										"description": "ID of the filament sensor hardware",
										"type": "string"
									},
									"connectedTo": {
										"description": "Where the filament sensor is connected to",
										"type": "string",
										"enum": ["toolboard", "controlboard"]
									}
								},
								"required": ["id", "connectedTo"]
							}
						},
						"required": ["extruder", "hotend", "xEndstop", "yEndstop", "axis", "partFan", "hotendFan"]
					},
					"minItems": 1
				},
				"board": {
					"description": "Default board for this printer. Should be the name of the board directory.",
					"type": "string"
				},
				"chamberLighting": {
					"description": "Default chamber lighting option for this printer.",
					"type": "object",
					"properties": {
						"id": {
							"description": "ID of the chamber lighting hardware",
							"type": "string"
						},
						"connectedTo": {
							"description": "Where the chamber lighting is connected to",
							"type": "string",
							"enum": ["toolboard", "controlboard"]
						}
					},
					"required": ["id", "connectedTo"]
				},
				"toolheadAlignmentSystem": {
					"description": "Default toolhead alignment system for this printer.",
					"type": "object",
					"properties": {
						"id": {
							"description": "ID of the toolhead alignment system hardware",
							"type": "string"
						},
						"connectedTo": {
							"description": "Where the toolhead alignment system is connected to",
							"type": "string",
							"enum": ["toolboard", "controlboard"]
						}
					},
					"required": ["id", "connectedTo"]
				},
				"chamberAirFilter": {
					"description": "Default chamber air filter for this printer.",
					"type": "object",
					"properties": {
						"id": {
							"description": "ID of the chamber air filter hardware",
							"type": "string"
						},
						"connectedTo": {
							"description": "Where the chamber air filter is connected to",
							"type": "string",
							"enum": ["toolboard", "controlboard"]
						}
					},
					"required": ["id", "connectedTo"]
				},
				"controllerFan": {
					"description": "Default controller fan for this printer.",
					"type": "string",
					"enum": [
						"2pin",
						"4pin",
						"4pin-dedicated",
						"2pin-toolboard",
						"4pin-toolboard",
						"4pin-dedicated-toolboard",
						"none"
					]
				},
				"rails": {
					"description": "Default rails for this printer.",
					"type": "array",
					"items": {
						"type": "object",
						"additionalProperties": false,
						"properties": {
							"axis": {
								"description": "Axis for this rail.",
								"type": "string",
								"enum": ["x", "x1", "dual_carriage", "y", "y1", "y2", "z", "z1", "z2", "z3", "extruder", "extruder1"]
							},
							"axisDescription": {
								"description": "Description of the axis for this rail such as where it's located on the printer",
								"type": "string"
							},
							"driver": {
								"description": "Default driver for this rail",
								"type": "string"
							},
							"voltage": {
								"description": "Default voltage for this rail. 24, 36, 48, 56 and 60 is supported. Default is 24.",
								"type": "number"
							},
							"stepper": {
								"description": "Default stepper for this rail",
								"type": "string"
							},
							"current": {
								"description": "Default current for this rail",
								"type": "number"
							},
							"performanceMode": {
								"description": "Defaults when in performance mode",
								"type": "object",
								"additionalProperties": false,
								"properties": {
									"voltage": {
										"description": "Default voltage for this rail. 24, 36, 48, 56 and 60 is supported. Default is 24.",
										"type": "number"
									},
									"current": {
										"description": "Default current for this rail in performance mode",
										"type": "number"
									},
									"homingSpeed": {
										"description": "Default homing speed for this rail in performance mode",
										"type": "number"
									}
								},
								"required": ["current"]
							},
							"rotationDistance": {
								"description": "Default rotation distance for this rail. Note: extruder axis rotation_distance should be 0, will be overridden by the extruder include.",
								"type": "number"
							},
							"gearRatio": {
								"description": "Optional gear ratio for this rail.",
								"type": "string"
							},
							"homingSpeed": {
								"description": "Default homing speed for this rail.",
								"type": "number"
							},
							"microstepping": {
								"description": "Default microstepping for this rail. Default is 64.",
								"type": "number"
							}
						},
						"required": ["axis", "axisDescription", "driver", "stepper", "current", "rotationDistance"]
					}
				}
			},
			"required": ["board", "rails", "toolheads"]
		}
	},
	"required": [
		"name",
		"description",
		"manufacturer",
		"documentationLink",
		"driverCountRequired",
		"image",
		"template",
		"defaults",
		"speedLimits"
	]
}

=== coolio986/ratical/configuration/printers/v-core-3-idex/printer-definition.json
{
	"$schema": "../printer-definition.schema.json",
	"name": "V-Core 3 IDEX",
	"description": "Ratical's former flagship CoreXY printer in IDEX Wideboy configuration, available in 4 sizes",
	"manufacturer": "Ratical",
	"documentationLink": "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
	"image": "rat-rig-v-core-3.png",
	"template": "v-core-3-idex-printer.template.cfg",
	"driverCountRequired": 9,
	"sizes": {
		"300": {
			"x": 300,
			"y": 300,
			"z": 300
		},
		"400": {
			"x": 400,
			"y": 400,
			"z": 400
		},
		"500": {
			"x": 500,
			"y": 500,
			"z": 500
		}
	},
	"bedMargin": {
		"x": [73.5, 73.5],
		"y": [0, 0]
	},
	"speedLimits": {
		"basic": {
			"accel": 3000,
			"velocity": 300,
			"z_accel": 50,
			"z_velocity": 30,
			"travel_accel": 3000,
			"travel_velocity": 300
		},
		"performance": {
			"accel": 10000,
			"velocity": 800,
			"z_accel": 600,
			"z_velocity": 50,
			"travel_velocity": 600,
			"travel_accel": 8000
		}
	},
	"kinematics": "hybrid-corexy-idex",
	"defaults": {
		"board": "btt-octopus-11",
		"toolheads": [
			{
				"axis": "x",
				"description": "The left toolhead",
				"extruder": "orbiter-2",
				"toolboard": "btt-ebb42-12",
				"hotend": "rapido",
				"partFan": "4pin-toolboard",
				"hotendFan": "2pin-toolboard",
				"probe": "superpinda",
				"xEndstop": "endstop-toolboard",
				"yEndstop": "endstop"
			},
			{
				"axis": "dual_carriage",
				"description": "The right toolhead",
				"extruder": "orbiter-2",
				"toolboard": "btt-ebb42-12",
				"hotend": "rapido",
				"partFan": "4pin-toolboard",
				"hotendFan": "2pin-toolboard",
				"probe": "superpinda",
				"xEndstop": "endstop-toolboard",
				"yEndstop": "endstop"
			}
		],
		"rails": [
			{
				"axis": "x",
				"axisDescription": "The X axis motor for the left toolhead, located at the rear left of the printer",
				"current": 1.1,
				"driver": "BTT-TMC2209-13",
				"stepper": "LDO-42STH48-2504AC",
				"rotationDistance": 40,
				"homingSpeed": 50,
				"performanceMode": {
					"current": 1.6
				}
			},
			{
				"axis": "dual_carriage",
				"axisDescription": "The X axis motor for the right toolhead, located at the rear right of the printer",
				"current": 1.1,
				"driver": "BTT-TMC2209-13",
				"stepper": "LDO-42STH48-2504AC",
				"rotationDistance": 40,
				"homingSpeed": 50,
				"performanceMode": {
					"current": 1.6
				}
			},
			{
				"axis": "y",
				"axisDescription": "The left Y motor used for cartesian Y control in Hybrid CoreXY, located at the rear left of the printer",
				"current": 1.1,
				"driver": "BTT-TMC2209-13",
				"stepper": "LDO-42STH48-2504AC",
				"rotationDistance": 40,
				"homingSpeed": 50,
				"performanceMode": {
					"current": 1.6
				}
			},
			{
				"axis": "y1",
				"axisDescription": "The right Y motor used for cartesian Y control in Hybrid CoreXY, located at the rear right of the printer",
				"current": 1.1,
				"driver": "BTT-TMC2209-13",
				"stepper": "LDO-42STH48-2504AC",
				"rotationDistance": 40,
				"homingSpeed": 50,
				"performanceMode": {
					"current": 1.6
				}
			},
			{
				"axis": "z",
				"axisDescription": "The left Z motor for the kinematic bed",
				"current": 1.1,
				"driver": "BTT-TMC2209-13",
				"stepper": "LDO-42STH48-2504AC",
				"rotationDistance": 4,
				"homingSpeed": 10,
				"performanceMode": {
					"current": 1.6
				}
			},
			{
				"axis": "z1",
				"axisDescription": "The rear Z motor for the kinematic bed",
				"current": 1.1,
				"driver": "BTT-TMC2209-13",
				"stepper": "LDO-42STH48-2504AC",
				"rotationDistance": 4,
				"performanceMode": {
					"current": 1.6
				}
			},
			{
				"axis": "z2",
				"axisDescription": "The right Z motor for the kinematic bed",
				"current": 1.1,
				"driver": "BTT-TMC2209-13",
				"stepper": "LDO-42STH48-2504AC",
				"rotationDistance": 4,
				"performanceMode": {
					"current": 1.6
				}
			},
			{
				"axis": "extruder",
				"axisDescription": "The extruder motor used for pushing filament through the left toolhead (T0)",
				"rotationDistance": 0,
				"current": 0.707,
				"driver": "BTT-TMC2209-13",
				"stepper": "LDO-36STH20-1004AHG"
			},
			{
				"axis": "extruder1",
				"axisDescription": "The extruder motor used for pushing filament through the right toolhead (T1)",
				"rotationDistance": 0,
				"current": 0.707,
				"driver": "BTT-TMC2209-13",
				"stepper": "LDO-36STH20-1004AHG"
			}
		]
	}
}

=== coolio986/ratical/configuration/printers/v-minion/printer-definition.json
{
	"$schema": "../printer-definition.schema.json",
	"name": "V-Minion",
	"description": "A small 180x180x180mm bed slinger from Ratical",
	"manufacturer": "Ratical",
	"documentationLink": "https://github.com/coolio986/ratical/docs/printers/v-minion",
	"image": "v-minion.png",
	"template": "v-minion-printer.template.cfg",
	"driverCountRequired": 4,
	"sizes": {
		"180": {
			"x": 180,
			"y": 180,
			"z": 180
		}
	},
	"speedLimits": {
		"basic": {
			"accel": 3000,
			"velocity": 200,
			"z_accel": 200,
			"z_velocity": 15,
			"travel_accel": 3000,
			"travel_velocity": 200
		},
		"performance": {
			"accel": 15000,
			"velocity": 600,
			"z_accel": 600,
			"z_velocity": 15,
			"travel_accel": 8000,
			"travel_velocity": 600
		}
	},
	"defaults": {
		"board": "btt-skrat-10",
		"toolheads": [
			{
				"axis": "x",
				"extruder": "lgx-lite",
				"hotend": "dragonfly",
				"partFan": "4pin",
				"hotendFan": "2pin",
				"probe": "probe",
				"xEndstop": "endstop",
				"yEndstop": "endstop"
			}
		],
		"rails": [
			{
				"axis": "x",
				"axisDescription": "The X axis motor moves the print head left and right.",
				"current": 0.8,
				"performanceMode": {
					"current": 1.188,
					"homingSpeed": 100
				},
				"driver": "BTT-TMC2209-13",
				"stepper": "LDO-42STH40-1684AC",
				"homingSpeed": 50,
				"rotationDistance": 40
			},
			{
				"axis": "y",
				"axisDescription": "The Y axis motor moves the print bed forward and backward.",
				"current": 0.8,
				"performanceMode": {
					"current": 1.188,
					"homingSpeed": 100
				},
				"driver": "BTT-TMC2209-13",
				"stepper": "LDO-42STH40-1684AC",
				"homingSpeed": 50,
				"rotationDistance": 40
			},
			{
				"axis": "z",
				"axisDescription": "The Z axis motor moves the print head up and down.",
				"current": 0.8,
				"performanceMode": {
					"current": 1.188
				},
				"driver": "BTT-TMC2209-13",
				"stepper": "LDO-42STH40-1684AC",
				"rotationDistance": 4
			},
			{
				"axis": "extruder",
				"axisDescription": "The extruder motor used for your toolhead",
				"current": 0.707,
				"driver": "BTT-TMC2209-13",
				"stepper": "LDO-36STH20-1004AHG",
				"rotationDistance": 0
			}
		]
	}
}

=== coolio986/ratical/configuration/printers/v-core-4-1-hybrid/printer-definition.json
{
	"$schema": "../printer-definition.schema.json",
	"name": "V-Core 4.1 Hybrid",
	"description": "Ratical flagship 3d printer with the hybrid upgrade kit",
	"manufacturer": "Ratical",
	"releaseDate": "2042-05-25",
	"documentationLink": "",
	"image": "v-core-4-hybrid.png",
	"template": "v-core-4-1-hybrid.ts",
	"driverCountRequired": 8,
	"sizes": {
		"300": {
			"x": 300,
			"y": 300,
			"z": 300
		},
		"400": {
			"x": 400,
			"y": 400,
			"z": 400
		},
		"500": {
			"x": 500,
			"y": 500,
			"z": 500
		}
	},
	"bedMargin": {
		"x": [60.6, 59.55],
		"y": [14.35, 30]
	},
	"speedLimits": {
		"basic": {
			"accel": 3000,
			"velocity": 300,
			"z_accel": 50,
			"z_velocity": 30,
			"travel_accel": 3000,
			"travel_velocity": 300
		},
		"performance": {
			"accel": 10000,
			"velocity": 800,
			"z_accel": 600,
			"z_velocity": 50,
			"travel_velocity": 600,
			"travel_accel": 8000
		}
	},
	"kinematics": "hybrid-corexy",
	"defaults": {
		"board": "btt-octopus-11",
		"chamberLighting": { "id": "dayspring", "connectedTo": "controlboard" },
		"toolheads": [
			{
				"axis": "x",
				"description": "the V-Core toolhead",
				"extruder": "orbiter-2",
				"toolboard": "ldo-orbitool-o2s",
				"hotend": "rapido-plus-uhf",
				"partFan": "4pin-dedicated-toolboard",
				"hotendFan": "2pin-toolboard",
				"probe": "beacon",
				"xEndstop": "endstop-toolboard",
				"yEndstop": "endstop",
				"filamentSensor": {"id": "orbiter-smart-sensor", "connectedTo": "toolboard"}
			}
		],
		"rails": [
			{
				"axis": "x",
				"axisDescription": "The A axis motor for the toolhead, located at the rear left of the printer",
				"current": 1.1,
				"driver": "BTT-TMC2209-13",
				"stepper": "LDO-42STH48-2504AC",
				"rotationDistance": 40,
				"homingSpeed": 50,
				"performanceMode": {
					"current": 1.6
				}
			},
			{
				"axis": "x1",
				"axisDescription": "The B axis motor for the toolhead, located at the rear right of the printer",
				"current": 1.1,
				"driver": "BTT-TMC2209-13",
				"stepper": "LDO-42STH48-2504AC",
				"rotationDistance": 40,
				"homingSpeed": 50,
				"performanceMode": {
					"current": 1.6
				}
			},
			{
				"axis": "y",
				"axisDescription": "The left Y motor used for cartesian Y control in Hybrid CoreXY, located at the rear left of the printer",
				"current": 1.1,
				"driver": "BTT-TMC2209-13",
				"stepper": "LDO-42STH48-2504AC",
				"rotationDistance": 40,
				"homingSpeed": 50,
				"performanceMode": {
					"current": 1.6
				}
			},
			{
				"axis": "y1",
				"axisDescription": "The right Y motor used for cartesian Y control in Hybrid CoreXY, located at the rear right of the printer",
				"current": 1.1,
				"driver": "BTT-TMC2209-13",
				"stepper": "LDO-42STH48-2504AC",
				"rotationDistance": 40,
				"homingSpeed": 50,
				"performanceMode": {
					"current": 1.6
				}
			},
			{
				"axis": "z",
				"axisDescription": "The left Z motor for the kinematic bed",
				"current": 1.1,
				"driver": "BTT-TMC2209-13",
				"stepper": "LDO-42STH48-2504AC",
				"rotationDistance": 4,
				"homingSpeed": 10,
				"performanceMode": {
					"current": 1.6
				}
			},
			{
				"axis": "z1",
				"axisDescription": "The rear Z motor for the kinematic bed",
				"current": 1.1,
				"driver": "BTT-TMC2209-13",
				"stepper": "LDO-42STH48-2504AC",
				"rotationDistance": 4,
				"performanceMode": {
					"current": 1.6
				}
			},
			{
				"axis": "z2",
				"axisDescription": "The right Z motor for the kinematic bed",
				"current": 1.1,
				"driver": "BTT-TMC2209-13",
				"stepper": "LDO-42STH48-2504AC",
				"rotationDistance": 4,
				"performanceMode": {
					"current": 1.6
				}
			},
			{
				"axis": "extruder",
				"axisDescription": "The extruder motor used for pushing filament through the toolhead",
				"rotationDistance": 0,
				"current": 0.707,
				"driver": "BTT-TMC2209-13",
				"stepper": "LDO-36STH20-1004AHG"
			}
		]
	}
}

=== coolio986/ratical/configuration/printers/prusa-mini/printer-definition.json
{
	"$schema": "../printer-definition.schema.json",
	"name": "Mini",
	"description": "Mini bed slinger from Prusa Research",
	"manufacturer": "Prusa",
	"documentationLink": "https://github.com/coolio986/ratical/docs/printers/prusa-mini",
	"image": "prusa-mini.webp",
	"template": "prusa-mini-printer.template.cfg",
	"driverCountRequired": 4,
	"speedLimits": {
		"basic": {
			"accel": 3000,
			"velocity": 165,
			"z_accel": 200,
			"z_velocity": 15
		},
		"performance": {
			"accel": 15000,
			"velocity": 400,
			"z_accel": 600,
			"z_velocity": 15
		}
	},
	"bedMargin": {
		"x": [2, 0.4],
		"y": [3, 0]
	},
	"sizes": {
		"180": {
			"x": 180,
			"y": 180,
			"z": 210
		}
	},
	"defaults": {
		"board": "prusa-buddy",
		"controllerFan": "none",
		"toolheads": [
			{
				"axis": "x",
				"partFan": "4pin-dedicated",
				"hotendFan": "4pin-dedicated",
				"extruder": "prusa-mini",
				"hotend": "v6",
				"probe": "superpinda",
				"xEndstop": "endstop",
				"yEndstop": "endstop"
			}
		],
		"rails": [
			{
				"axis": "x",
				"axisDescription": "The X axis motor moves the print head left and right.",
				"current": 0.4,
				"performanceMode": {
					"current": 1.188
				},
				"rotationDistance": 32,
				"driver": "PRUSA-BUDDY-TMC2209",
				"stepper": "LDO-42STH40-1684AC"
			},
			{
				"axis": "y",
				"axisDescription": "The Y axis motor moves the print bed forward and backward.",
				"current": 0.4,
				"performanceMode": {
					"current": 1.188
				},
				"rotationDistance": 32,
				"driver": "PRUSA-BUDDY-TMC2209",
				"stepper": "LDO-42STH40-1684AC"
			},
			{
				"axis": "z",
				"axisDescription": "The Z axis motor moves the print head up and down.",
				"current": 0.4,
				"performanceMode": {
					"current": 1.188
				},
				"rotationDistance": 4,
				"driver": "PRUSA-BUDDY-TMC2209",
				"stepper": "LDO-42STH40-1684AC"
			},
			{
				"axis": "extruder",
				"axisDescription": "The extruder motor used for your toolhead",
				"current": 0.5,
				"driver": "PRUSA-BUDDY-TMC2209",
				"stepper": "generic",
				"rotationDistance": 0
			}
		]
	}
}

=== coolio986/ratical/configuration/printers/v-core-3/printer-definition.json
{
	"$schema": "../printer-definition.schema.json",
	"name": "V-Core 3",
	"description": "Ratical's former flagship CoreXY printer in 4 sizes",
	"manufacturer": "Ratical",
	"documentationLink": "https://github.com/coolio986/ratical/docs/printers/v-core-3",
	"image": "rat-rig-v-core-3.png",
	"template": "v-core-3-printer.template.cfg",
	"driverCountRequired": 6,
	"sizes": {
		"200": {
			"x": 200,
			"y": 200,
			"z": 200
		},
		"300": {
			"x": 300,
			"y": 300,
			"z": 300
		},
		"400": {
			"x": 400,
			"y": 400,
			"z": 400
		},
		"500": {
			"x": 500,
			"y": 500,
			"z": 500
		}
	},
	"speedLimits": {
		"basic": {
			"accel": 3000,
			"velocity": 300,
			"z_accel": 50,
			"z_velocity": 30,
			"travel_accel": 3000,
			"travel_velocity": 300
		},
		"performance": {
			"accel": 10000,
			"velocity": 800,
			"z_accel": 600,
			"z_velocity": 50,
			"travel_velocity": 600,
			"travel_accel": 8000
		}
	},
	"defaults": {
		"board": "btt-octopus-11",
		"toolheads": [
			{
				"axis": "x",
				"extruder": "lgx-lite",
				"hotend": "rapido",
				"partFan": "4pin",
				"hotendFan": "2pin",
				"probe": "superpinda",
				"xEndstop": "endstop",
				"yEndstop": "endstop"
			}
		],
		"rails": [
			{
				"axis": "x",
				"axisDescription": "The A motor in the CoreXY system, located at the rear left of the printer",
				"current": 1.1,
				"driver": "BTT-TMC2209-13",
				"stepper": "LDO-42STH48-2504AC",
				"rotationDistance": 40,
				"homingSpeed": 50,
				"performanceMode": {
					"current": 1.6
				}
			},
			{
				"axis": "y",
				"axisDescription": "The B motor in the CoreXY system, located at the rear right of the printer",
				"current": 1.1,
				"driver": "BTT-TMC2209-13",
				"stepper": "LDO-42STH48-2504AC",
				"rotationDistance": 40,
				"homingSpeed": 50,
				"performanceMode": {
					"current": 1.6
				}
			},
			{
				"axis": "z",
				"axisDescription": "The left Z motor for the kinematic bed",
				"current": 1.1,
				"driver": "BTT-TMC2209-13",
				"stepper": "LDO-42STH48-2504AC",
				"rotationDistance": 4,
				"homingSpeed": 10,
				"performanceMode": {
					"current": 1.6
				}
			},
			{
				"axis": "z1",
				"axisDescription": "The rear Z motor for the kinematic bed",
				"current": 1.1,
				"driver": "BTT-TMC2209-13",
				"stepper": "LDO-42STH48-2504AC",
				"rotationDistance": 4,
				"performanceMode": {
					"current": 1.6
				}
			},
			{
				"axis": "z2",
				"axisDescription": "The right Z motor for the kinematic bed",
				"current": 1.1,
				"driver": "BTT-TMC2209-13",
				"stepper": "LDO-42STH48-2504AC",
				"rotationDistance": 4,
				"performanceMode": {
					"current": 1.6
				}
			},
			{
				"axis": "extruder",
				"axisDescription": "The extruder motor used for pushing filament through the toolhead",
				"rotationDistance": 0,
				"current": 0.707,
				"driver": "BTT-TMC2209-13",
				"stepper": "LDO-36STH20-1004AHG"
			}
		]
	}
}

=== coolio986/ratical/configuration/printers/voron-v01/printer-definition.json
{
	"$schema": "../printer-definition.schema.json",
	"name": "V0.1",
	"description": "Mini CoreXY printer from Voron Design",
	"manufacturer": "Voron Design",
	"documentationLink": "https://github.com/coolio986/ratical/docs/printers/v-minion",
	"image": "voron-v0.png",
	"template": "voron-v01-printer.template.cfg",
	"driverCountRequired": 4,
	"sizes": {
		"120": {
			"x": 120,
			"y": 120,
			"z": 120
		}
	},
	"speedLimits": {
		"basic": {
			"accel": 2000,
			"velocity": 200,
			"z_accel": 45,
			"z_velocity": 15,
			"travel_accel": 2000,
			"travel_velocity": 200
		},
		"performance": {
			"accel": 12000,
			"velocity": 600,
			"z_accel": 45,
			"z_velocity": 15,
			"square_corner_velocity": 6,
			"travel_accel": 8000,
			"travel_velocity": 600
		}
	},
	"defaults": {
		"board": "btt-skr-mini-e3-30",
		"toolheads": [
			{
				"axis": "x",
				"extruder": "mini-afterburner",
				"hotend": "dragonfly",
				"partFan": "4pin",
				"hotendFan": "2pin",
				"xEndstop": "endstop",
				"yEndstop": "endstop"
			}
		],
		"rails": [
			{
				"axis": "x",
				"axisDescription": "The A motor in the CoreXY system",
				"current": 0.5,
				"driver": "BTT-TMC2209-13",
				"stepper": "LDO-35STH48-1684AH",
				"microstepping": 128,
				"performanceMode": {
					"current": 1.0,
					"homingSpeed": 100
				},
				"rotationDistance": 40,
				"homingSpeed": 50
			},
			{
				"axis": "y",
				"axisDescription": "The B motor in the CoreXY system",
				"current": 0.5,
				"driver": "BTT-TMC2209-13",
				"stepper": "LDO-35STH48-1684AH",
				"microstepping": 128,
				"performanceMode": {
					"current": 1.0,
					"homingSpeed": 100
				},
				"rotationDistance": 40,
				"homingSpeed": 50
			},
			{
				"axis": "z",
				"axisDescription": "The Z motor that moves the bed",
				"current": 0.707,
				"driver": "BTT-TMC2209-13",
				"stepper": "LDO-42STH25-1004CL200E",
				"microstepping": 128,
				"performanceMode": {
					"current": 0.707,
					"homingSpeed": 100
				},
				"rotationDistance": 8,
				"homingSpeed": 50
			},
			{
				"axis": "extruder",
				"axisDescription": "The extruder motor used for your toolhead",
				"current": 0.35,
				"driver": "BTT-TMC2209-13",
				"stepper": "LDO-36STH17-1004AHG",
				"microstepping": 128,
				"rotationDistance": 0
			}
		]
	}
}
